options:
  limit-to-first-requester:
    default: True
    type: boolean
    description: |
      Limit requested identifiers (hostnames, IPs and OIDs) to first requester
  limit-to-one-request:
    default: False
    type: boolean
    description: |
      Limit to one request will only allow a single CSR from any requirer
