options:
  limit-to-one-request:
    default: False
    type: boolean
    description: |
      Limit to one request will only allow a single CSR from any requirer
  
  allowed-dns:
    default: ""
    type: string
    description: |
      Regex for describing custom filtering options for DNS's. Ex: "myapp-([0-9]+)?\.mycompany\.com"
  allowed-ips:
    default: ""
    type: string
    description: |
      Regex for describing custom filtering options for IP's. Ex: "172\.25\.0\.[0-9]*"
  allowed-oids:
    default: ""
    type: string
    description: |
      Regex for describing custom filtering options for OID's. Ex: "1\.3\.6\.1\.4\.1\.28978\.[0-9.]*"
  allowed-common-name:
    default: ""
    type: string
    description: |
      Regex for describing custom filtering options for common names. Ex: "myapp-([0-9]+)?\.mycompany\.com"
  allowed-organization:
    default: ""
    type: string
    description: |
      Regex for describing custom filtering options for organizations. Ex: "Canonical Ltd\."
  allowed-email:
    default: ""
    type: string
    description: |
      Regex for describing custom filtering options for emails. Ex: ".*@canonical\.com"
  allowed-country-code:
    default: ""
    type: string
    description: |
      Regex for describing custom filtering options for country codes. Ex: "(UK|US|CA|PL|AE|HU|FR|TR|IT)$"